name: .NET Core

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: src  
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Version 
      run: echo "::set-env name=package_version::$major_version.$minor_version.$GITHUB_RUN_NUMBER"
      env:
        major_version: 1
        minor_version: 0
    - name: Test Verion 
      run: echo $package_version
      
    #- name: Setup .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.101
    #    key: installnet
    #- name: Install dependencies
    #  run: dotnet restore
    
   # - name: Build
   #   run: dotnet build --configuration Release --no-restore
      
   # - name: Pack
   #   run: dotnet pack --configuration Release
